id: P8D9E3E48
initial_creation_type: ocr
source_metadata:
  volumes:
    850477d849204e43a8dd4b8676344b98:
      base_file: v093.txt
      image_group_id: I1PD95938
      title: གཞུང་ལུགས་ཀྱི་བྱེ་བྲག་བཀོད་པའི་འཁོར་ལོ།
      total_pages: 1484
      volume_number: 93
